# Generated by Django 4.1.5 on 2023-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
